spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8070
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8111/realms/master/protocol/openid-connect/certs

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8072

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"
